### ISSUE TITLE
Download interrupted without error

### ISSUE THREAD

**Issue by Greg-Lim** [vignedev/twist-dl#20]
Download will freeze and the program will be exited with out any warnings or error.
`Episode 11 (1/3) [==......................] 1478340/bps 7% 102.6s
C:\Users\auser\folder>`

Could be due to loading too fast.

**Comment by Ragnyll** [comment]
I'm experiencing this too.

**Comment by vignedev** [comment]
Their servers have started to interrupt the downloads after some time. The issue is that for whatever reason, node-fetch does not report the premature ending and shuts down the entire Node process. I'll investigate further on what the options are.

The current possible workaround, although not perfect in any way, is to run the program multiple times, since twist-dl is able to restore partial downloads.

Also, may I ask you what are your Node versions?

**Comment by Greg-Lim** [comment]
> Their servers have started to interrupt the downloads after some time. The issue is that for whatever reason, node-fetch does not report the premature ending and shuts down the entire Node process. I'll investigate further on what the options are.
> 
> The current possible workaround, although not perfect in any way, is to run the program multiple times, since twist-dl is able to restore partial downloads.
> 
> Also, may I ask you what are your Node versions?

**Comment by Greg-Lim** [comment]
> Also, may I ask you what are your Node versions?

v14.15.1
